/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  PostApiAuthLogin200,
  PostApiAuthLoginBody,
  PostApiAuthRefresh200,
  PostApiAuthRefreshBody,
  PostApiAuthRegisterAdmin201,
  PostApiAuthRegisterAdminBody
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Authenticate user with email/phone and password
 * @summary User login
 */
export const postApiAuthLogin = (
    postApiAuthLoginBody: PostApiAuthLoginBody,
 ) => {
      
      
      return mutator<PostApiAuthLogin200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthLoginBody
    },
      );
    }
  


export const getPostApiAuthLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: PostApiAuthLoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: PostApiAuthLoginBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data: PostApiAuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = PostApiAuthLoginBody
    export type PostApiAuthLoginMutationError = void

    /**
 * @summary User login
 */
export const usePostApiAuthLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: PostApiAuthLoginBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data: PostApiAuthLoginBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get a new access token using a valid refresh token
 * @summary Refresh access token
 */
export const postApiAuthRefresh = (
    postApiAuthRefreshBody: PostApiAuthRefreshBody,
 ) => {
      
      
      return mutator<PostApiAuthRefresh200>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRefreshBody
    },
      );
    }
  


export const getPostApiAuthRefreshMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: PostApiAuthRefreshBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: PostApiAuthRefreshBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefresh>>, {data: PostApiAuthRefreshBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRefresh(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefresh>>>
    export type PostApiAuthRefreshMutationBody = PostApiAuthRefreshBody
    export type PostApiAuthRefreshMutationError = void

    /**
 * @summary Refresh access token
 */
export const usePostApiAuthRefresh = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,{data: PostApiAuthRefreshBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        {data: PostApiAuthRefreshBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRefreshMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Create a new admin user account (requires SITE_MANAGER_KEY)
 * @summary Register a new admin (Site Manager only)
 */
export const postApiAuthRegisterAdmin = (
    postApiAuthRegisterAdminBody: PostApiAuthRegisterAdminBody,
 ) => {
      
      
      return mutator<PostApiAuthRegisterAdmin201>(
      {url: `/api/auth/register-admin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRegisterAdminBody
    },
      );
    }
  


export const getPostApiAuthRegisterAdminMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegisterAdmin>>, TError,{data: PostApiAuthRegisterAdminBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegisterAdmin>>, TError,{data: PostApiAuthRegisterAdminBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegisterAdmin>>, {data: PostApiAuthRegisterAdminBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegisterAdmin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterAdminMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegisterAdmin>>>
    export type PostApiAuthRegisterAdminMutationBody = PostApiAuthRegisterAdminBody
    export type PostApiAuthRegisterAdminMutationError = void

    /**
 * @summary Register a new admin (Site Manager only)
 */
export const usePostApiAuthRegisterAdmin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegisterAdmin>>, TError,{data: PostApiAuthRegisterAdminBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRegisterAdmin>>,
        TError,
        {data: PostApiAuthRegisterAdminBody},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRegisterAdminMutationOptions(options);

      return useMutation(mutationOptions);
    }
    