/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApiPositions200Item,
  GetApiPositionsId200
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Retrieve all positions for the election
 * @summary Get all positions
 */
export const getApiPositions = (
    
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiPositions200Item[]>(
      {url: `/api/positions`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiPositionsQueryKey = () => {
    return [`/api/positions`] as const;
    }

    
export const getGetApiPositionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPositions>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPositions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPositionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPositions>>> = ({ signal }) => getApiPositions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPositions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiPositionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPositions>>>
export type GetApiPositionsQueryError = void

/**
 * @summary Get all positions
 */
export const useGetApiPositions = <TData = Awaited<ReturnType<typeof getApiPositions>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPositions>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiPositionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve detailed information about a specific position
 * @summary Get single position
 */
export const getApiPositionsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiPositionsId200>(
      {url: `/api/positions/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiPositionsIdQueryKey = (id: string,) => {
    return [`/api/positions/${id}`] as const;
    }

    
export const getGetApiPositionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPositionsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPositionsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPositionsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPositionsId>>> = ({ signal }) => getApiPositionsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPositionsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiPositionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPositionsId>>>
export type GetApiPositionsIdQueryError = void

/**
 * @summary Get single position
 */
export const useGetApiPositionsId = <TData = Awaited<ReturnType<typeof getApiPositionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPositionsId>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiPositionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



