/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
export type PostApiVotingCast200 = {
  ballotId?: string;
  message?: string;
  timestamp?: string;
  votesCount?: number;
};

export type PostApiVotingCastBodyVotesItem = {
  /**
   * Candidate ID (null for abstain)
   * @nullable
   */
  candidateId?: string | null;
  /** Position ID to vote for */
  positionId: string;
};

export type PostApiVotingCastBody = {
  votes: PostApiVotingCastBodyVotesItem[];
};

export type GetApiVotingElection200VotingStatus = {
  canVote?: boolean;
  hasVoted?: boolean;
  votedPositions?: string[];
};

export type GetApiVotingElection200 = {
  election?: GetApiVotingElection200Election;
  votingStatus?: GetApiVotingElection200VotingStatus;
};

export type GetApiVotingElection200ElectionPositionsItemCandidatesItem = {
  bio?: string;
  classYearGroup?: string;
  fullName?: string;
  id?: string;
  photoUrl?: string;
};

export type GetApiVotingElection200ElectionPositionsItem = {
  candidates?: GetApiVotingElection200ElectionPositionsItemCandidatesItem[];
  id?: string;
  name?: string;
  order?: number;
};

export type GetApiVotingElection200Election = {
  description?: string;
  id?: string;
  positions?: GetApiVotingElection200ElectionPositionsItem[];
  title?: string;
};

export type PostApiVotingVerifyOtpBody = {
  /** 6-digit OTP code */
  code: string;
  /** Voter's phone number in international format */
  phone: string;
};

export type PostApiVotingRequestOtp200 = {
  message?: string;
  phone?: string;
};

export type PostApiVotingRequestOtpBody = {
  /** Voter's phone number */
  phone: string;
};

export type PostApiVotingLogout200 = {
  message?: string;
};

export type DeleteApiVotersId200 = {
  message?: string;
};

export type PutApiVotersId200 = {
  classYearGroup?: string;
  fullName?: string;
  id?: string;
  phone?: string;
  status?: string;
  uniqueIdentifier?: string;
  updatedAt?: string;
};

export type PutApiVotersIdBody = {
  /** Class year group of the voter */
  classYearGroup: string;
  /**
   * Full name of the voter
   * @minLength 2
   */
  fullName: string;
  /** Ghana phone number */
  phone: string;
  /** Status of the voter */
  status?: string;
  /** Unique identifier for the voter */
  uniqueIdentifier: string;
};

export type PostApiVoters201 = {
  classYearGroup?: string;
  createdAt?: string;
  fullName?: string;
  id?: string;
  phone?: string;
  status?: string;
  uniqueIdentifier?: string;
};

export type PostApiVotersBody = {
  /** Class year group of the voter */
  classYearGroup: string;
  /**
   * Full name of the voter
   * @minLength 2
   */
  fullName: string;
  /** Ghana phone number */
  phone: string;
  /** Status of the voter */
  status?: string;
  /** Unique identifier for the voter */
  uniqueIdentifier: string;
};

export type GetApiVoters200VotersItem = {
  classYearGroup?: string;
  createdAt?: string;
  fullName?: string;
  id?: string;
  isVerified?: boolean;
  phone?: string;
  status?: string;
  uniqueIdentifier?: string;
};

export type GetApiVoters200Pagination = {
  limit?: number;
  page?: number;
  total?: number;
  totalPages?: number;
};

export type GetApiVoters200 = {
  pagination?: GetApiVoters200Pagination;
  voters?: GetApiVoters200VotersItem[];
};

export type GetApiVotersParams = {
/**
 * Page number for pagination
 */
page?: string;
/**
 * Number of voters per page
 */
limit?: string;
/**
 * Search term for name, phone, or unique identifier
 */
search?: string;
/**
 * Filter by voter status
 */
status?: string;
/**
 * Filter by class year group
 */
classYearGroup?: string;
};

export type GetApiResultsPublicElectionId200ElectionPositionsItemCandidatesItem = {
  classYearGroup?: string;
  id?: string;
  name?: string;
  percentage?: number;
  /** @nullable */
  photoUrl?: string | null;
  votes?: number;
};

export type GetApiResultsPublicElectionId200ElectionPositionsItem = {
  candidates?: GetApiResultsPublicElectionId200ElectionPositionsItemCandidatesItem[];
  id?: string;
  name?: string;
};

export type GetApiResultsPublicElectionId200Election = {
  id?: string;
  positions?: GetApiResultsPublicElectionId200ElectionPositionsItem[];
  status?: string;
  title?: string;
};

export type GetApiResultsPublicElectionId200 = {
  election?: GetApiResultsPublicElectionId200Election;
  totalBallots?: number;
  totalVoters?: number;
  turnoutRate?: number;
};

export type GetApiResultsLiveElectionId200 = {
  election?: GetApiResultsLiveElectionId200Election;
  totalBallots?: number;
  totalVoters?: number;
};

export type GetApiResultsLiveElectionId200ElectionPositionsItemCandidatesItem = {
  classYearGroup?: string;
  id?: string;
  name?: string;
  percentage?: number;
  /** @nullable */
  photoUrl?: string | null;
  votes?: number;
};

export type GetApiResultsLiveElectionId200ElectionPositionsItem = {
  candidates?: GetApiResultsLiveElectionId200ElectionPositionsItemCandidatesItem[];
  id?: string;
  name?: string;
};

export type GetApiResultsLiveElectionId200Election = {
  id?: string;
  positions?: GetApiResultsLiveElectionId200ElectionPositionsItem[];
  status?: string;
  title?: string;
};

export type GetApiPositionsId200VotesItemCandidate = {
  fullName?: string;
  id?: string;
};

export type GetApiPositionsId200VotesItem = {
  candidate?: GetApiPositionsId200VotesItemCandidate;
  id?: string;
};

export type GetApiPositionsId200Election = {
  id?: string;
  status?: string;
  title?: string;
};

export type GetApiPositionsId200CandidatesItem = {
  fullName?: string;
  id?: string;
  order?: number;
};

export type GetApiPositionsId200 = {
  candidates?: GetApiPositionsId200CandidatesItem[];
  description?: string;
  election?: GetApiPositionsId200Election;
  id?: string;
  isActive?: boolean;
  maxCandidates?: number;
  name?: string;
  order?: number;
  votes?: GetApiPositionsId200VotesItem[];
};

export type GetApiPositions200ItemCandidatesItem = {
  fullName?: string;
  id?: string;
  order?: number;
};

export type _GetApiPositions200ItemCount = {
  votes?: number;
};

export type GetApiPositions200Item = {
  _count?: _GetApiPositions200ItemCount;
  candidates?: GetApiPositions200ItemCandidatesItem[];
  description?: string;
  id?: string;
  isActive?: boolean;
  maxCandidates?: number;
  name?: string;
  order?: number;
};

export type GetApiElectionsId200PositionsItemCandidatesItem = {
  fullName?: string;
  id?: string;
  order?: number;
};

export type GetApiElectionsId200PositionsItem = {
  candidates?: GetApiElectionsId200PositionsItemCandidatesItem[];
  id?: string;
  name?: string;
};

export type GetApiElectionsId200 = {
  description?: string;
  endDate?: string;
  id?: string;
  isActive?: boolean;
  positions?: GetApiElectionsId200PositionsItem[];
  startDate?: string;
  title?: string;
};

export type GetApiElections200ItemPositionsItemCandidatesItem = {
  fullName?: string;
  id?: string;
  isActive?: boolean;
};

export type GetApiElections200ItemPositionsItem = {
  candidates?: GetApiElections200ItemPositionsItemCandidatesItem[];
  id?: string;
  name?: string;
};

export type GetApiElections200Item = {
  description?: string;
  endDate?: string;
  id?: string;
  isActive?: boolean;
  positions?: GetApiElections200ItemPositionsItem[];
  startDate?: string;
  title?: string;
};

export type GetApiDisputes200Pagination = {
  limit?: number;
  page?: number;
  pages?: number;
  total?: number;
};

export type GetApiDisputes200 = {
  disputes?: GetApiDisputes200DisputesItem[];
  pagination?: GetApiDisputes200Pagination;
};

export type GetApiDisputes200DisputesItemPosition = {
  id?: string;
  name?: string;
};

export type GetApiDisputes200DisputesItemElection = {
  id?: string;
  status?: string;
  title?: string;
};

export type GetApiDisputes200DisputesItemCreator = {
  id?: string;
  name?: string;
  role?: string;
};

export type GetApiDisputes200DisputesItemCandidate = {
  classYearGroup?: string;
  fullName?: string;
  id?: string;
};

export type GetApiDisputes200DisputesItemAssignee = {
  id?: string;
  name?: string;
  role?: string;
};

export type GetApiDisputes200DisputesItem = {
  assignee?: GetApiDisputes200DisputesItemAssignee;
  candidate?: GetApiDisputes200DisputesItemCandidate;
  createdAt?: string;
  creator?: GetApiDisputes200DisputesItemCreator;
  description?: string;
  election?: GetApiDisputes200DisputesItemElection;
  /** @nullable */
  evidence?: string | null;
  id?: string;
  position?: GetApiDisputes200DisputesItemPosition;
  status?: string;
  title?: string;
};

export type GetApiDisputesParams = {
/**
 * Filter by dispute status
 */
status?: string;
/**
 * Filter by election ID
 */
electionId?: string;
/**
 * Page number for pagination
 */
page?: string;
/**
 * Number of disputes per page
 */
limit?: string;
};

export type GetApiCandidates200ItemPosition = {
  id?: string;
  name?: string;
  order?: number;
};

export type _GetApiCandidates200ItemCount = {
  votes?: number;
};

export type GetApiCandidates200Item = {
  _count?: _GetApiCandidates200ItemCount;
  bio?: string;
  email?: string;
  fullName?: string;
  id?: string;
  isActive?: boolean;
  manifesto?: string;
  order?: number;
  phone?: string;
  position?: GetApiCandidates200ItemPosition;
};

export type GetApiCandidatesPositionPositionId200ItemPositionElection = {
  id?: string;
  status?: string;
  title?: string;
};

export type GetApiCandidatesPositionPositionId200ItemPosition = {
  election?: GetApiCandidatesPositionPositionId200ItemPositionElection;
  id?: string;
  name?: string;
};

export type _GetApiCandidatesPositionPositionId200ItemCount = {
  votes?: number;
};

export type GetApiCandidatesPositionPositionId200Item = {
  _count?: _GetApiCandidatesPositionPositionId200ItemCount;
  bio?: string;
  email?: string;
  fullName?: string;
  id?: string;
  isActive?: boolean;
  manifesto?: string;
  order?: number;
  phone?: string;
  position?: GetApiCandidatesPositionPositionId200ItemPosition;
};

export type PostApiAuthRegisterAdmin201Admin = {
  id?: string;
  name?: string;
  phone?: string;
  role?: string;
};

export type PostApiAuthRegisterAdmin201 = {
  admin?: PostApiAuthRegisterAdmin201Admin;
  message?: string;
};

export type PostApiAuthRegisterAdminBodyRole = typeof PostApiAuthRegisterAdminBodyRole[keyof typeof PostApiAuthRegisterAdminBodyRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiAuthRegisterAdminBodyRole = {
  ADMIN: 'ADMIN',
  EC_MEMBER: 'EC_MEMBER',
  ADVISORY_COUNCIL: 'ADVISORY_COUNCIL',
} as const;

export type PostApiAuthRegisterAdminBody = {
  /**
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** @minLength 8 */
  password: string;
  /** Admin's phone number */
  phone: string;
  role?: PostApiAuthRegisterAdminBodyRole;
  /** Site manager authentication key */
  siteManagerKey: string;
};

export type PostApiAuthRefresh200User = {
  /** @nullable */
  email?: string | null;
  id?: string;
  name?: string;
  /** @nullable */
  phone?: string | null;
  role?: string;
};

export type PostApiAuthRefresh200 = {
  accessToken?: string;
  refreshToken?: string;
  user?: PostApiAuthRefresh200User;
};

export type PostApiAuthRefreshBody = {
  /** Valid refresh token */
  refreshToken: string;
};

export type PostApiAuthLogin200User = {
  /** @nullable */
  email?: string | null;
  id?: string;
  name?: string;
  /** @nullable */
  phone?: string | null;
  role?: string;
};

export type PostApiAuthLogin200 = {
  accessToken?: string;
  refreshToken?: string;
  user?: PostApiAuthLogin200User;
};

export type PostApiAuthLoginBody = (unknown & {
  /** User's email address */
  email?: string;
  /**
   * User's password
   * @minLength 6
   */
  password?: string;
  /** User's phone number */
  phone?: string;
}) | (unknown & {
  /** User's email address */
  email?: string;
  /**
   * User's password
   * @minLength 6
   */
  password?: string;
  /** User's phone number */
  phone?: string;
});

export type PostApiAuthLogout200 = {
  message?: string;
};

/**
 * Breakdown of voters by status
 */
export type GetApiAdminDashboard200VoterStatusBreakdown = {[key: string]: number};

export type GetApiAdminDashboard200Statistics = {
  /** Number of currently active elections */
  activeElections?: number;
  /** Total number of ballots cast */
  totalBallots?: number;
  /** Total number of elections */
  totalElections?: number;
  /** Total number of registered voters */
  totalVoters?: number;
  /** Voter turnout percentage */
  turnoutRate?: number;
};

/**
 * SMS message statistics by status
 */
export type GetApiAdminDashboard200SmsStats = {[key: string]: number};

export type GetApiAdminDashboard200 = {
  recentActivity?: GetApiAdminDashboard200RecentActivityItem[];
  /** SMS message statistics by status */
  smsStats?: GetApiAdminDashboard200SmsStats;
  statistics?: GetApiAdminDashboard200Statistics;
  /** Breakdown of voters by status */
  voterStatusBreakdown?: GetApiAdminDashboard200VoterStatusBreakdown;
};

export type GetApiAdminDashboard200RecentActivityItemVoter = {
  fullName?: string;
};

export type GetApiAdminDashboard200RecentActivityItemUser = {
  name?: string;
  role?: string;
};

export type GetApiAdminDashboard200RecentActivityItem = {
  action?: string;
  id?: string;
  timestamp?: string;
  user?: GetApiAdminDashboard200RecentActivityItemUser;
  voter?: GetApiAdminDashboard200RecentActivityItemVoter;
};

