/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApiDisputes200,
  GetApiDisputesParams
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Retrieve a paginated list of all disputes with optional filtering
 * @summary Get all disputes
 */
export const getApiDisputes = (
    params?: GetApiDisputesParams,
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiDisputes200>(
      {url: `/api/disputes`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetApiDisputesQueryKey = (params?: GetApiDisputesParams,) => {
    return [`/api/disputes`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiDisputesQueryOptions = <TData = Awaited<ReturnType<typeof getApiDisputes>>, TError = void>(params?: GetApiDisputesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDisputes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDisputesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDisputes>>> = ({ signal }) => getApiDisputes(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDisputes>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiDisputesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDisputes>>>
export type GetApiDisputesQueryError = void

/**
 * @summary Get all disputes
 */
export const useGetApiDisputes = <TData = Awaited<ReturnType<typeof getApiDisputes>>, TError = void>(
 params?: GetApiDisputesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDisputes>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiDisputesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



