/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApiVotingElection200,
  PostApiVotingCast200,
  PostApiVotingCastBody,
  PostApiVotingRequestOtp200,
  PostApiVotingRequestOtpBody,
  PostApiVotingVerifyOtpBody
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Request a one-time password to authenticate a voter for voting
 * @summary Request OTP for voting
 */
export const postApiVotingRequestOtp = (
    postApiVotingRequestOtpBody: PostApiVotingRequestOtpBody,
 ) => {
      
      
      return mutator<PostApiVotingRequestOtp200>(
      {url: `/api/voting/request-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiVotingRequestOtpBody
    },
      );
    }
  


export const getPostApiVotingRequestOtpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVotingRequestOtp>>, TError,{data: PostApiVotingRequestOtpBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiVotingRequestOtp>>, TError,{data: PostApiVotingRequestOtpBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVotingRequestOtp>>, {data: PostApiVotingRequestOtpBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiVotingRequestOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiVotingRequestOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVotingRequestOtp>>>
    export type PostApiVotingRequestOtpMutationBody = PostApiVotingRequestOtpBody
    export type PostApiVotingRequestOtpMutationError = void

    /**
 * @summary Request OTP for voting
 */
export const usePostApiVotingRequestOtp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVotingRequestOtp>>, TError,{data: PostApiVotingRequestOtpBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiVotingRequestOtp>>,
        TError,
        {data: PostApiVotingRequestOtpBody},
        TContext
      > => {

      const mutationOptions = getPostApiVotingRequestOtpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Verify the one-time password sent to the voter via SMS
 * @summary Verify OTP for voting
 */
export const postApiVotingVerifyOtp = (
    postApiVotingVerifyOtpBody: PostApiVotingVerifyOtpBody,
 ) => {
      
      
      return mutator<void>(
      {url: `/api/voting/verify-otp`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiVotingVerifyOtpBody
    },
      );
    }
  


export const getPostApiVotingVerifyOtpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVotingVerifyOtp>>, TError,{data: PostApiVotingVerifyOtpBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiVotingVerifyOtp>>, TError,{data: PostApiVotingVerifyOtpBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVotingVerifyOtp>>, {data: PostApiVotingVerifyOtpBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiVotingVerifyOtp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiVotingVerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVotingVerifyOtp>>>
    export type PostApiVotingVerifyOtpMutationBody = PostApiVotingVerifyOtpBody
    export type PostApiVotingVerifyOtpMutationError = void

    /**
 * @summary Verify OTP for voting
 */
export const usePostApiVotingVerifyOtp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVotingVerifyOtp>>, TError,{data: PostApiVotingVerifyOtpBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiVotingVerifyOtp>>,
        TError,
        {data: PostApiVotingVerifyOtpBody},
        TContext
      > => {

      const mutationOptions = getPostApiVotingVerifyOtpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get the current active election with positions and candidates, plus voter's voting status
 * @summary Get current election and voting status
 */
export const getApiVotingElection = (
    
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiVotingElection200>(
      {url: `/api/voting/election`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiVotingElectionQueryKey = () => {
    return [`/api/voting/election`] as const;
    }

    
export const getGetApiVotingElectionQueryOptions = <TData = Awaited<ReturnType<typeof getApiVotingElection>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVotingElection>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiVotingElectionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiVotingElection>>> = ({ signal }) => getApiVotingElection(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiVotingElection>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiVotingElectionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiVotingElection>>>
export type GetApiVotingElectionQueryError = void

/**
 * @summary Get current election and voting status
 */
export const useGetApiVotingElection = <TData = Awaited<ReturnType<typeof getApiVotingElection>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVotingElection>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiVotingElectionQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Submit votes for all election positions at once
 * @summary Cast votes for all positions
 */
export const postApiVotingCast = (
    postApiVotingCastBody: PostApiVotingCastBody,
 ) => {
      
      
      return mutator<PostApiVotingCast200>(
      {url: `/api/voting/cast`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiVotingCastBody
    },
      );
    }
  


export const getPostApiVotingCastMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVotingCast>>, TError,{data: PostApiVotingCastBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiVotingCast>>, TError,{data: PostApiVotingCastBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVotingCast>>, {data: PostApiVotingCastBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiVotingCast(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiVotingCastMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVotingCast>>>
    export type PostApiVotingCastMutationBody = PostApiVotingCastBody
    export type PostApiVotingCastMutationError = void

    /**
 * @summary Cast votes for all positions
 */
export const usePostApiVotingCast = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVotingCast>>, TError,{data: PostApiVotingCastBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiVotingCast>>,
        TError,
        {data: PostApiVotingCastBody},
        TContext
      > => {

      const mutationOptions = getPostApiVotingCastMutationOptions(options);

      return useMutation(mutationOptions);
    }
    