/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApiElections200Item,
  GetApiElectionsId200
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Retrieve a list of all elections with their positions and candidates
 * @summary Get all elections
 */
export const getApiElections = (
    
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiElections200Item[]>(
      {url: `/api/elections`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiElectionsQueryKey = () => {
    return [`/api/elections`] as const;
    }

    
export const getGetApiElectionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiElections>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiElections>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiElectionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiElections>>> = ({ signal }) => getApiElections(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiElections>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiElectionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiElections>>>
export type GetApiElectionsQueryError = void

/**
 * @summary Get all elections
 */
export const useGetApiElections = <TData = Awaited<ReturnType<typeof getApiElections>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiElections>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiElectionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve detailed information about a specific election
 * @summary Get single election
 */
export const getApiElectionsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiElectionsId200>(
      {url: `/api/elections/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiElectionsIdQueryKey = (id: string,) => {
    return [`/api/elections/${id}`] as const;
    }

    
export const getGetApiElectionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiElectionsId>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiElectionsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiElectionsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiElectionsId>>> = ({ signal }) => getApiElectionsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiElectionsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiElectionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiElectionsId>>>
export type GetApiElectionsIdQueryError = void

/**
 * @summary Get single election
 */
export const useGetApiElectionsId = <TData = Awaited<ReturnType<typeof getApiElectionsId>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiElectionsId>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiElectionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



