/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  DeleteApiVotersId200,
  GetApiVoters200,
  GetApiVotersParams,
  PostApiVoters201,
  PostApiVotersBody,
  PutApiVotersId200,
  PutApiVotersIdBody
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Retrieve a paginated list of voters with optional filtering and search
 * @summary Get all voters
 */
export const getApiVoters = (
    params?: GetApiVotersParams,
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiVoters200>(
      {url: `/api/voters`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetApiVotersQueryKey = (params?: GetApiVotersParams,) => {
    return [`/api/voters`, ...(params ? [params]: [])] as const;
    }

    
export const getGetApiVotersQueryOptions = <TData = Awaited<ReturnType<typeof getApiVoters>>, TError = void>(params?: GetApiVotersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVoters>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiVotersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiVoters>>> = ({ signal }) => getApiVoters(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiVoters>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiVotersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiVoters>>>
export type GetApiVotersQueryError = void

/**
 * @summary Get all voters
 */
export const useGetApiVoters = <TData = Awaited<ReturnType<typeof getApiVoters>>, TError = void>(
 params?: GetApiVotersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVoters>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiVotersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new voter with the provided information
 * @summary Create new voter
 */
export const postApiVoters = (
    postApiVotersBody: PostApiVotersBody,
 ) => {
      
      
      return mutator<PostApiVoters201>(
      {url: `/api/voters`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiVotersBody
    },
      );
    }
  


export const getPostApiVotersMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVoters>>, TError,{data: PostApiVotersBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiVoters>>, TError,{data: PostApiVotersBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVoters>>, {data: PostApiVotersBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiVoters(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiVotersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVoters>>>
    export type PostApiVotersMutationBody = PostApiVotersBody
    export type PostApiVotersMutationError = void

    /**
 * @summary Create new voter
 */
export const usePostApiVoters = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVoters>>, TError,{data: PostApiVotersBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof postApiVoters>>,
        TError,
        {data: PostApiVotersBody},
        TContext
      > => {

      const mutationOptions = getPostApiVotersMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Update an existing voter's information
 * @summary Update voter
 */
export const putApiVotersId = (
    id: string,
    putApiVotersIdBody: PutApiVotersIdBody,
 ) => {
      
      
      return mutator<PutApiVotersId200>(
      {url: `/api/voters/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiVotersIdBody
    },
      );
    }
  


export const getPutApiVotersIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiVotersId>>, TError,{id: string;data: PutApiVotersIdBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiVotersId>>, TError,{id: string;data: PutApiVotersIdBody}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiVotersId>>, {id: string;data: PutApiVotersIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiVotersId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiVotersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiVotersId>>>
    export type PutApiVotersIdMutationBody = PutApiVotersIdBody
    export type PutApiVotersIdMutationError = void

    /**
 * @summary Update voter
 */
export const usePutApiVotersId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiVotersId>>, TError,{id: string;data: PutApiVotersIdBody}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof putApiVotersId>>,
        TError,
        {id: string;data: PutApiVotersIdBody},
        TContext
      > => {

      const mutationOptions = getPutApiVotersIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Soft delete a voter (marks as inactive)
 * @summary Delete voter
 */
export const deleteApiVotersId = (
    id: string,
 ) => {
      
      
      return mutator<DeleteApiVotersId200>(
      {url: `/api/voters/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiVotersIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiVotersId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiVotersId>>, TError,{id: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiVotersId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiVotersId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiVotersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiVotersId>>>
    
    export type DeleteApiVotersIdMutationError = void

    /**
 * @summary Delete voter
 */
export const useDeleteApiVotersId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiVotersId>>, TError,{id: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiVotersId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiVotersIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    