/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Voting API
 * Secure voting system API — Express, TypeScript, Prisma. Auto-generated from JSDoc comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetApiCandidates200Item,
  GetApiCandidatesPositionPositionId200Item
} from '../votingAPI.schemas'
import { mutator } from '../../api-client';



/**
 * Retrieve all candidates for a specific position
 * @summary Get candidates by position
 */
export const getApiCandidatesPositionPositionId = (
    positionId: string,
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiCandidatesPositionPositionId200Item[]>(
      {url: `/api/candidates/position/${positionId}`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiCandidatesPositionPositionIdQueryKey = (positionId: string,) => {
    return [`/api/candidates/position/${positionId}`] as const;
    }

    
export const getGetApiCandidatesPositionPositionIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>, TError = void>(positionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCandidatesPositionPositionIdQueryKey(positionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>> = ({ signal }) => getApiCandidatesPositionPositionId(positionId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(positionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiCandidatesPositionPositionIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>>
export type GetApiCandidatesPositionPositionIdQueryError = void

/**
 * @summary Get candidates by position
 */
export const useGetApiCandidatesPositionPositionId = <TData = Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>, TError = void>(
 positionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCandidatesPositionPositionId>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiCandidatesPositionPositionIdQueryOptions(positionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieve all candidates for the election
 * @summary Get all candidates
 */
export const getApiCandidates = (
    
 signal?: AbortSignal
) => {
      
      
      return mutator<GetApiCandidates200Item[]>(
      {url: `/api/candidates`, method: 'GET', signal
    },
      );
    }
  

export const getGetApiCandidatesQueryKey = () => {
    return [`/api/candidates`] as const;
    }

    
export const getGetApiCandidatesQueryOptions = <TData = Awaited<ReturnType<typeof getApiCandidates>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCandidates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCandidatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCandidates>>> = ({ signal }) => getApiCandidates(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCandidates>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiCandidatesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCandidates>>>
export type GetApiCandidatesQueryError = void

/**
 * @summary Get all candidates
 */
export const useGetApiCandidates = <TData = Awaited<ReturnType<typeof getApiCandidates>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCandidates>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetApiCandidatesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



